services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - db
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  backend:
    build: ./backend
    environment:
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      PORT: ${PORT_BACKEND}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db
    ports:
      - "${PORT_BACKEND}:${PORT_BACKEND}"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
  services:
    php_service:
      build: ./php_service
      volumes:
      - ./php_service/manual:/app/manual  # Monta el PDF local
      - ./php_service/src:/app/src
      - ./php_service/composer.json:/app/composer.json
      - ./php_service/composer.lock:/app/composer.lock
      ports:
        - "8080:8080"
      depends_on:
        - db

volumes:
  pgdata:
  pgadmin_data:
